# Generated by Django 5.0.2 on 2025-12-04 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_buap_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('nrc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('seccion', models.IntegerField()),
                ('dias', models.CharField(max_length=255)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('salon', models.CharField(max_length=255)),
                ('programa_educativo', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_buap_api.maestros')),
            ],
        ),
    ]
